#title:q-distance

#tags:geof:distance
#color:ex-green
#img:

select distinct (geof:distance(?xGeom, ?yGeom, <http://www.opengis.net/def/uom/OGC/1.0/metre>) as ?dist)
where {
	?x geo:asWKT ?xGeom.
	?y geo:asWKT ?yGeom.
}