#title:Landmarks withing the Polygon
#comment:Landmarks with coordinates withing the Polygon

#tags:geof:sfWithin,polygon,filter
#color:ex-blue
#img:
  
SELECT *
WHERE {
  ?lmA a ex:Landmark ;
       geo:hasGeometry ?Geom.

  ?Geom geo:asWKT ?WKT.

  FILTER(geof:sfWithin(?WKT, '''
        <http://www.opengis.net/def/crs/OGC/1.3/CRS84>
            Polygon ((90 90, -90 90, -90 -90, 90 -90, 90 90))
        '''^^geo:wktLiteral))
}