#title:Connected-equipment
#comment:

#tags:wkt,coordinates
#color:ex-green
#img:

SELECT DISTINCT ?condEqId1 ?condEqName1 ?condEqId2 ?condEqName2
WHERE {
  ?termId1 rdf:type cim:Terminal.
  ?termId1 cim:IdentifiedObject.name ?termName1.
  ?termId2 rdf:type cim:Terminal.
  ?termId1 cim:IdentifiedObject.name ?termName2.
  
	?termId1 cim:Terminal.ConductingEquipment ?condEqId1.
  ?condEqId1 cim:IdentifiedObject.name ?condEqName1.
  ?termId1 cim:Terminal.ConnectivityNode ?conNodeId1.
  
  
  ?termId2 cim:Terminal.ConductingEquipment ?condEqId2.
  ?condEqId2 cim:IdentifiedObject.name ?condEqName2.
  ?termId2 cim:Terminal.ConnectivityNode ?conNodeId2.
  
  FILTER(?conNodeId1 = ?conNodeId2)
  FILTER(str(?termId1) < str(?termId2))
}