#title:Connected-equipment
#comment:

#tags:connected-equipment
#color:ex-green
#img:

select DISTINCT ?condEqName ?postionPointId1 ?postionPointId2
where {
  #terminals
  ?tmId rdf:type cim:Terminal.
  ?tmId cim:IdentifiedObject.name ?tmName.
   
  #connectivity nodes of terminal
  ?tmId cim:Terminal.ConnectivityNode ?cNodeId.
  ?cNodeId cim:IdentifiedObject.name ?cNodeName.
  
  #conducting equipment of terminal
  ?tmId cim:Terminal.ConductingEquipment ?condEqId.
  ?condEqId cim:IdentifiedObject.name ?condEqName.
  
  #locations
  ?condEqId cim:PowerSystemResource.Location ?locationId.
  ?postionPointId1 rdf:type cim:PositionPoint.
  ?postionPointId2 rdf:type cim:PositionPoint.
  
  ?postionPointId1 cim:PositionPoint.Location ?locationId.
  ?postionPointId2 cim:PositionPoint.Location ?locationId.
}