#title:Connected-equipment-coordinates
#comment:

#tags:connected-points,coordinates
#color:ex-green
#img:

select DISTINCT ?xPosition1 ?yPosition1 ?xPosition2 ?yPosition2
where {
  #terminals
  ?tmId rdf:type cim:Terminal.
  ?tmId cim:IdentifiedObject.name ?tmName.
   
  #connectivity nodes of terminal
  ?tmId cim:Terminal.ConnectivityNode ?cNodeId.
  ?cNodeId cim:IdentifiedObject.name ?cNodeName.
  
  #conducting equipment of terminal
  ?tmId cim:Terminal.ConductingEquipment ?condEqId.
  ?condEqId cim:IdentifiedObject.name ?condEqName.
  
  #locations
  ?condEqId cim:PowerSystemResource.Location ?locationId.
  ?postionPointId1 rdf:type cim:PositionPoint.
  ?postionPointId2 rdf:type cim:PositionPoint.
  
  ?postionPointId1 cim:PositionPoint.Location ?locationId.
  ?postionPointId2 cim:PositionPoint.Location ?locationId.
  
  
  #coordinates
  ?postionPointId1 cim:PositionPoint.xPosition ?xPosition1.
  ?postionPointId1 cim:PositionPoint.yPosition ?yPosition1.
  
  ?postionPointId2 cim:PositionPoint.xPosition ?xPosition2.
  ?postionPointId2 cim:PositionPoint.yPosition ?yPosition2.
}