#title:draw-hazard
#comment:

#tags:hazard,polygons,wkt,coordinates
#color:ex-green
#img:

select DISTINCT *
where { 
  #hazard zones
  ?hazardType rdfs:subClassOf+ custom:Hazard. 
  ?stormId rdf:type ?hazardType.
  ?stormId custom:Hazard.DangerZone ?g_wktStorm.
}