//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Set of attributes of an asset, representing typical datasheet information of a physical device that can be instantiated and shared in different data exchange contexts:
    ///- as attributes of an asset instance (installed or in stock)
    ///- as attributes of an asset model (product by a manufacturer)
    ///- as attributes of a type asset (generic type of an asset as used in designs/extension planning).
    public class AssetInfo : IdentifiedObject {
    }
}
