//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A collection of equipment for organizational purposes, used for grouping distribution resources.
    ///The organization a feeder does not necessarily reflect connectivity or current operation state.
    public class Feeder : EquipmentContainer {
    }
}
