//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// This is a root class to provide common identification for all classes needing identification and naming attributes.
    public class IdentifiedObject : IDClass {
        
        /// The aliasName is free text human readable name of the object alternative to IdentifiedObject.name. It may be non unique and may not correlate to a naming hierarchy.
        ///The attribute aliasName is retained because of backwards compatibility between CIM relases. It is however recommended to replace aliasName with the Name class as aliasName is planned for retirement at a future time.
        private string cim_aliasName;
        
        private const bool isAliasNameMandatory = false;
        
        private const string _aliasNamePrefix = "cim";
        
        /// The description is a free human readable text describing or naming the object. It may be non unique and may not correlate to a naming hierarchy.
        private string cim_description;
        
        private const bool isDescriptionMandatory = false;
        
        private const string _descriptionPrefix = "cim";
        
        /// Master resource identifier issued by a model authority. The mRID is unique within an exchange context. Global uniqueness is easily achieved by using a UUID, as specified in RFC 4122, for the mRID. The use of UUID is strongly recommended.
        ///For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.
        private string cim_mRID;
        
        private const bool isMRIDMandatory = false;
        
        private const string _mRIDPrefix = "cim";
        
        /// The name is any free human readable and possibly non unique text naming the object.
        private string cim_name;
        
        private const bool isNameMandatory = false;
        
        private const string _namePrefix = "cim";
        
        public virtual string AliasName {
            get {
                return this.cim_aliasName;
            }
            set {
                this.cim_aliasName = value;
            }
        }
        
        public virtual bool AliasNameHasValue {
            get {
                return this.cim_aliasName != null;
            }
        }
        
        public static bool IsAliasNameMandatory {
            get {
                return isAliasNameMandatory;
            }
        }
        
        public static string AliasNamePrefix {
            get {
                return _aliasNamePrefix;
            }
        }
        
        public virtual string Description {
            get {
                return this.cim_description;
            }
            set {
                this.cim_description = value;
            }
        }
        
        public virtual bool DescriptionHasValue {
            get {
                return this.cim_description != null;
            }
        }
        
        public static bool IsDescriptionMandatory {
            get {
                return isDescriptionMandatory;
            }
        }
        
        public static string DescriptionPrefix {
            get {
                return _descriptionPrefix;
            }
        }
        
        public virtual string MRID {
            get {
                return this.cim_mRID;
            }
            set {
                this.cim_mRID = value;
            }
        }
        
        public virtual bool MRIDHasValue {
            get {
                return this.cim_mRID != null;
            }
        }
        
        public static bool IsMRIDMandatory {
            get {
                return isMRIDMandatory;
            }
        }
        
        public static string MRIDPrefix {
            get {
                return _mRIDPrefix;
            }
        }
        
        public virtual string Name {
            get {
                return this.cim_name;
            }
            set {
                this.cim_name = value;
            }
        }
        
        public virtual bool NameHasValue {
            get {
                return this.cim_name != null;
            }
        }
        
        public static bool IsNameMandatory {
            get {
                return isNameMandatory;
            }
        }
        
        public static string NamePrefix {
            get {
                return _namePrefix;
            }
        }
    }
}
