//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// The place, scene, or point of something where someone or something has been, is, and/or will be at a given moment in time. It can be defined with one or more position points (coordinates) in a given coordinate system.
    public class Location : IdentifiedObject {
        
        /// Coordinate system used to describe position points of this location.
        private CoordinateSystem cim_CoordinateSystem;
        
        private const bool isCoordinateSystemMandatory = false;
        
        private const string _CoordinateSystemPrefix = "cim";
        
        /// (if applicable) Direction that allows field crews to quickly find a given asset. For a given location, such as a street address, this is the relative direction in which to find the asset. For example, a streetlight may be located at the 'NW' (northwest) corner of the customer's site, or a usage point may be located on the second floor of an apartment building.
        private string cim_direction;
        
        private const bool isDirectionMandatory = false;
        
        private const string _directionPrefix = "cim";
        
        /// Electronic address.
        private ElectronicAddress cim_electronicAddress;
        
        private const bool isElectronicAddressMandatory = false;
        
        private const string _electronicAddressPrefix = "cim";
        
        /// (if applicable) Reference to geographical information source, often external to the utility.
        private string cim_geoInfoReference;
        
        private const bool isGeoInfoReferenceMandatory = false;
        
        private const string _geoInfoReferencePrefix = "cim";
        
        /// Main address of the location.
        private StreetAddress cim_mainAddress;
        
        private const bool isMainAddressMandatory = false;
        
        private const string _mainAddressPrefix = "cim";
        
        /// Phone number.
        private TelephoneNumber cim_phone1;
        
        private const bool isPhone1Mandatory = false;
        
        private const string _phone1Prefix = "cim";
        
        /// Additional phone number.
        private TelephoneNumber cim_phone2;
        
        private const bool isPhone2Mandatory = false;
        
        private const string _phone2Prefix = "cim";
        
        /// Secondary address of the location. For example, PO Box address may have different ZIP code than that in the 'mainAddress'.
        private StreetAddress cim_secondaryAddress;
        
        private const bool isSecondaryAddressMandatory = false;
        
        private const string _secondaryAddressPrefix = "cim";
        
        /// Status of this location.
        private Status cim_status;
        
        private const bool isStatusMandatory = false;
        
        private const string _statusPrefix = "cim";
        
        /// Classification by utility's corporate standards and practices, relative to the location itself (e.g., geographical, functional accounting, etc., not a given property that happens to exist at that location).
        private string cim_type;
        
        private const bool isTypeMandatory = false;
        
        private const string _typePrefix = "cim";
        
        public virtual CoordinateSystem CoordinateSystem {
            get {
                return this.cim_CoordinateSystem;
            }
            set {
                this.cim_CoordinateSystem = value;
            }
        }
        
        public virtual bool CoordinateSystemHasValue {
            get {
                return this.cim_CoordinateSystem != null;
            }
        }
        
        public static bool IsCoordinateSystemMandatory {
            get {
                return isCoordinateSystemMandatory;
            }
        }
        
        public static string CoordinateSystemPrefix {
            get {
                return _CoordinateSystemPrefix;
            }
        }
        
        public virtual string Direction {
            get {
                return this.cim_direction;
            }
            set {
                this.cim_direction = value;
            }
        }
        
        public virtual bool DirectionHasValue {
            get {
                return this.cim_direction != null;
            }
        }
        
        public static bool IsDirectionMandatory {
            get {
                return isDirectionMandatory;
            }
        }
        
        public static string DirectionPrefix {
            get {
                return _directionPrefix;
            }
        }
        
        public virtual ElectronicAddress ElectronicAddress {
            get {
                return this.cim_electronicAddress;
            }
            set {
                this.cim_electronicAddress = value;
            }
        }
        
        public virtual bool ElectronicAddressHasValue {
            get {
                return this.cim_electronicAddress != null;
            }
        }
        
        public static bool IsElectronicAddressMandatory {
            get {
                return isElectronicAddressMandatory;
            }
        }
        
        public static string ElectronicAddressPrefix {
            get {
                return _electronicAddressPrefix;
            }
        }
        
        public virtual string GeoInfoReference {
            get {
                return this.cim_geoInfoReference;
            }
            set {
                this.cim_geoInfoReference = value;
            }
        }
        
        public virtual bool GeoInfoReferenceHasValue {
            get {
                return this.cim_geoInfoReference != null;
            }
        }
        
        public static bool IsGeoInfoReferenceMandatory {
            get {
                return isGeoInfoReferenceMandatory;
            }
        }
        
        public static string GeoInfoReferencePrefix {
            get {
                return _geoInfoReferencePrefix;
            }
        }
        
        public virtual StreetAddress MainAddress {
            get {
                return this.cim_mainAddress;
            }
            set {
                this.cim_mainAddress = value;
            }
        }
        
        public virtual bool MainAddressHasValue {
            get {
                return this.cim_mainAddress != null;
            }
        }
        
        public static bool IsMainAddressMandatory {
            get {
                return isMainAddressMandatory;
            }
        }
        
        public static string MainAddressPrefix {
            get {
                return _mainAddressPrefix;
            }
        }
        
        public virtual TelephoneNumber Phone1 {
            get {
                return this.cim_phone1;
            }
            set {
                this.cim_phone1 = value;
            }
        }
        
        public virtual bool Phone1HasValue {
            get {
                return this.cim_phone1 != null;
            }
        }
        
        public static bool IsPhone1Mandatory {
            get {
                return isPhone1Mandatory;
            }
        }
        
        public static string Phone1Prefix {
            get {
                return _phone1Prefix;
            }
        }
        
        public virtual TelephoneNumber Phone2 {
            get {
                return this.cim_phone2;
            }
            set {
                this.cim_phone2 = value;
            }
        }
        
        public virtual bool Phone2HasValue {
            get {
                return this.cim_phone2 != null;
            }
        }
        
        public static bool IsPhone2Mandatory {
            get {
                return isPhone2Mandatory;
            }
        }
        
        public static string Phone2Prefix {
            get {
                return _phone2Prefix;
            }
        }
        
        public virtual StreetAddress SecondaryAddress {
            get {
                return this.cim_secondaryAddress;
            }
            set {
                this.cim_secondaryAddress = value;
            }
        }
        
        public virtual bool SecondaryAddressHasValue {
            get {
                return this.cim_secondaryAddress != null;
            }
        }
        
        public static bool IsSecondaryAddressMandatory {
            get {
                return isSecondaryAddressMandatory;
            }
        }
        
        public static string SecondaryAddressPrefix {
            get {
                return _secondaryAddressPrefix;
            }
        }
        
        public virtual Status Status {
            get {
                return this.cim_status;
            }
            set {
                this.cim_status = value;
            }
        }
        
        public virtual bool StatusHasValue {
            get {
                return this.cim_status != null;
            }
        }
        
        public static bool IsStatusMandatory {
            get {
                return isStatusMandatory;
            }
        }
        
        public static string StatusPrefix {
            get {
                return _statusPrefix;
            }
        }
        
        public virtual string Type {
            get {
                return this.cim_type;
            }
            set {
                this.cim_type = value;
            }
        }
        
        public virtual bool TypeHasValue {
            get {
                return this.cim_type != null;
            }
        }
        
        public static bool IsTypeMandatory {
            get {
                return isTypeMandatory;
            }
        }
        
        public static string TypePrefix {
            get {
                return _typePrefix;
            }
        }
    }
}
