//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum PhaseShuntConnectionKind {
        
        /// Delta connection.
        D,
        
        /// Ground connection; use when explicit connection to ground needs to be expressed in combination with the phase code, such as for electrical wire/cable or for meters.
        G,
        
        /// Independent winding, for single-phase connections.
        I,
        
        /// Wye connection.
        Y,
        
        /// Wye, with neutral brought out for grounding.
        Yn,
    }
}
