//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Set of spatial coordinates that determine a point, defined in the coordinate system specified in 'Location.CoordinateSystem'. Use a single position point instance to describe a point-oriented location. Use a sequence of position points to describe a line-oriented object (physical location of non-point oriented objects like cables or lines), or area of an object (like a substation or a geographical zone - in this case, have first and last position point with the same values).
    public class PositionPoint : IDClass {
        
        /// Zero-relative sequence number of this group within a series of points; used when there is a need to express disjoint groups of points that are considered to be part of a single location.
        private System.Int32? cim_groupNumber;
        
        private const bool isGroupNumberMandatory = false;
        
        private const string _groupNumberPrefix = "cim";
        
        /// Location described by this position point.
        private Location cim_Location;
        
        private const bool isLocationMandatory = true;
        
        private const string _LocationPrefix = "cim";
        
        /// Zero-relative sequence number of this point within a series of points.
        private System.Int32? cim_sequenceNumber;
        
        private const bool isSequenceNumberMandatory = false;
        
        private const string _sequenceNumberPrefix = "cim";
        
        /// X axis position.
        private string cim_xPosition;
        
        private const bool isXPositionMandatory = false;
        
        private const string _xPositionPrefix = "cim";
        
        /// Y axis position.
        private string cim_yPosition;
        
        private const bool isYPositionMandatory = false;
        
        private const string _yPositionPrefix = "cim";
        
        /// (if applicable) Z axis position.
        private string cim_zPosition;
        
        private const bool isZPositionMandatory = false;
        
        private const string _zPositionPrefix = "cim";
        
        public virtual int GroupNumber {
            get {
                return this.cim_groupNumber.GetValueOrDefault();
            }
            set {
                this.cim_groupNumber = value;
            }
        }
        
        public virtual bool GroupNumberHasValue {
            get {
                return this.cim_groupNumber != null;
            }
        }
        
        public static bool IsGroupNumberMandatory {
            get {
                return isGroupNumberMandatory;
            }
        }
        
        public static string GroupNumberPrefix {
            get {
                return _groupNumberPrefix;
            }
        }
        
        public virtual Location Location {
            get {
                return this.cim_Location;
            }
            set {
                this.cim_Location = value;
            }
        }
        
        public virtual bool LocationHasValue {
            get {
                return this.cim_Location != null;
            }
        }
        
        public static bool IsLocationMandatory {
            get {
                return isLocationMandatory;
            }
        }
        
        public static string LocationPrefix {
            get {
                return _LocationPrefix;
            }
        }
        
        public virtual int SequenceNumber {
            get {
                return this.cim_sequenceNumber.GetValueOrDefault();
            }
            set {
                this.cim_sequenceNumber = value;
            }
        }
        
        public virtual bool SequenceNumberHasValue {
            get {
                return this.cim_sequenceNumber != null;
            }
        }
        
        public static bool IsSequenceNumberMandatory {
            get {
                return isSequenceNumberMandatory;
            }
        }
        
        public static string SequenceNumberPrefix {
            get {
                return _sequenceNumberPrefix;
            }
        }
        
        public virtual string XPosition {
            get {
                return this.cim_xPosition;
            }
            set {
                this.cim_xPosition = value;
            }
        }
        
        public virtual bool XPositionHasValue {
            get {
                return this.cim_xPosition != null;
            }
        }
        
        public static bool IsXPositionMandatory {
            get {
                return isXPositionMandatory;
            }
        }
        
        public static string XPositionPrefix {
            get {
                return _xPositionPrefix;
            }
        }
        
        public virtual string YPosition {
            get {
                return this.cim_yPosition;
            }
            set {
                this.cim_yPosition = value;
            }
        }
        
        public virtual bool YPositionHasValue {
            get {
                return this.cim_yPosition != null;
            }
        }
        
        public static bool IsYPositionMandatory {
            get {
                return isYPositionMandatory;
            }
        }
        
        public static string YPositionPrefix {
            get {
                return _yPositionPrefix;
            }
        }
        
        public virtual string ZPosition {
            get {
                return this.cim_zPosition;
            }
            set {
                this.cim_zPosition = value;
            }
        }
        
        public virtual bool ZPositionHasValue {
            get {
                return this.cim_zPosition != null;
            }
        }
        
        public static bool IsZPositionMandatory {
            get {
                return isZPositionMandatory;
            }
        }
        
        public static string ZPositionPrefix {
            get {
                return _zPositionPrefix;
            }
        }
    }
}
