//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.
    public class PowerSystemResource : IdentifiedObject {
        
        /// Datasheet information for this power system resource.
        private AssetInfo cim_AssetDatasheet;
        
        private const bool isAssetDatasheetMandatory = false;
        
        private const string _AssetDatasheetPrefix = "cim";
        
        /// Location of this power system resource.
        private Location cim_Location;
        
        private const bool isLocationMandatory = false;
        
        private const string _LocationPrefix = "cim";
        
        public virtual AssetInfo AssetDatasheet {
            get {
                return this.cim_AssetDatasheet;
            }
            set {
                this.cim_AssetDatasheet = value;
            }
        }
        
        public virtual bool AssetDatasheetHasValue {
            get {
                return this.cim_AssetDatasheet != null;
            }
        }
        
        public static bool IsAssetDatasheetMandatory {
            get {
                return isAssetDatasheetMandatory;
            }
        }
        
        public static string AssetDatasheetPrefix {
            get {
                return _AssetDatasheetPrefix;
            }
        }
        
        public virtual Location Location {
            get {
                return this.cim_Location;
            }
            set {
                this.cim_Location = value;
            }
        }
        
        public virtual bool LocationHasValue {
            get {
                return this.cim_Location != null;
            }
        }
        
        public static bool IsLocationMandatory {
            get {
                return isLocationMandatory;
            }
        }
        
        public static string LocationPrefix {
            get {
                return _LocationPrefix;
            }
        }
    }
}
