//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum UnitMultiplier {
        
        /// Atto 10**-18.
        a,
        
        /// Centi 10**-2.
        c,
        
        /// Deci 10**-1.
        d,
        
        /// Deca 10**1.
        da,
        
        /// Exa 10**18.
        E,
        
        /// Femto 10**-15.
        f,
        
        /// Giga 10**9.
        G,
        
        /// Hecto 10**2.
        h,
        
        /// Kilo 10**3.
        k,
        
        /// Milli 10**-3.
        m,
        
        /// Mega 10**6.
        M,
        
        /// Micro 10**-6.
        micro,
        
        /// Nano 10**-9.
        n,
        
        /// No multiplier or equivalently multiply by 1.
        none,
        
        /// Pico 10**-12.
        p,
        
        /// Peta 10**15.
        P,
        
        /// Tera 10**12.
        T,
        
        /// Yocto 10**-24.
        y,
        
        /// Yotta 10**24.
        Y,
        
        /// Zepto 10**-21.
        z,
        
        /// Zetta 10**21.
        Z,
    }
}
