//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum UnitSymbol {
        
        /// Current in amperes.
        A,
        
        /// Amperes squared (A˛).
        A2,
        
        /// Ampere-squared hour, ampere-squared hour.
        A2h,
        
        /// Ampere squared time in square amperes (A˛s).
        A2s,
        
        /// Ampere-hours, ampere-hours.
        Ah,
        
        /// Plane angle, minutes.
        anglemin,
        
        /// Plane angle, seconds.
        anglesec,
        
        /// Current, ratio of amperages.   Note: Users may need to supply a prefix such as ‘m’ to show rates such as ‘mA/A’.
        APerA,
        
        /// A/m, magnetic field strength, amperes per metre.
        APerm,
        
        /// Ampere seconds (A·s).
        As,
        
        /// Pressure in bars, (1 bar = 100 kPa).
        bar,
        
        /// Radioactivity in becquerels (1/s).
        Bq,
        
        /// Energy, British Thermal Units.
        Btu,
        
        /// Electric charge in coulombs (A·s).
        C,
        
        /// Luminous intensity in candelas.
        cd,
        
        /// Number of characters.
        character,
        
        /// Data rate (baud) in characters per second.
        charPers,
        
        /// Power factor, dimensionless.
        ///Note 1: This definition of power factor only holds for balanced systems. See the alternative definition under code 153.
        ///Note 2 : Beware of differing sign conventions in use between the IEC and EEI. It is assumed that the data consumer understands the type of meter in use and the sign convention in use by the utility.
        cosPhi,
        
        /// Amount of substance, Counter value.
        count,
        
        /// Exposure (x rays), coulombs per kilogram.
        CPerkg,
        
        /// Surface charge density, coulombs per square metre.
        CPerm2,
        
        /// Electric charge density, coulombs per cubic metre.
        CPerm3,
        
        /// Time in days, day = 24 h = 86400 s.
        d,
        
        /// Sound pressure level in decibels. Note:  multiplier “d” is included in this unit symbol for compatibility with IEC 61850-7-3.
        dB,
        
        /// Power level (logarithmic ratio of signal strength , Bel-mW), normalized to 1mW. Note:  multiplier “d” is included in this unit symbol for compatibility with IEC 61850-7-3.
        dBm,
        
        /// Plane angle in degrees.
        deg,
        
        /// Relative temperature in degrees Celsius.
        ///In the SI unit system the symbol is °C. Electric charge is measured in coulomb that has the unit symbol C. To distinguish degree Celsius from coulomb the symbol used in the UML is degC. The reason for not using °C is that the special character ° is difficult to manage in software.
        degC,
        
        /// Electric capacitance in farads (C/V).
        F,
        
        /// Permittivity, farads per metre.
        FPerm,
        
        /// Volume, cubic feet.
        ft3,
        
        /// Magnetic flux density, gausses (1 G = 10-4 T).
        G,
        
        /// Volume in gallons, US gallon (1 gal = 231 in3 = 128 fl ounce).
        gal,
        
        /// Concentration, The ratio of the mass of a solute divided by the mass of  the solution. Note: Users may need use a prefix such a ‘µ’ to express a quantity such as ‘µg/g’.
        gPerg,
        
        /// Absorbed dose in grays (J/kg).
        Gy,
        
        /// Absorbed dose rate, grays per second.
        GyPers,
        
        /// Time in hours, hour = 60 min = 3600 s.
        h,
        
        /// Electric inductance in henrys (Wb/A).
        H,
        
        /// Area, hectares.
        ha,
        
        /// Permeability, henrys per metre.
        HPerm,
        
        /// Frequency in hertz (1/s).
        Hz,
        
        /// Frequency, rate of frequency change.   Note: Users may need to supply a prefix such as ‘m’ to show rates such as ‘mHz/Hz’.
        HzPerHz,
        
        /// Rate of change of frequency in hertz per second.
        HzPers,
        
        /// Energy in joules (N·m = C·V = W·s).
        J,
        
        /// Heat capacity in joules/kelvin.
        JPerK,
        
        /// Specific energy, Joules / kg.
        JPerkg,
        
        /// Specific heat capacity, specific entropy, joules per kilogram Kelvin.
        JPerkgK,
        
        /// Insulation energy density, joules per square metre or watt second per square metre.
        JPerm2,
        
        /// Energy density, joules per cubic metre.
        JPerm3,
        
        /// Molar energy, joules per mole.
        JPermol,
        
        /// Molar entropy, molar heat capacity, joules per mole kelvin.
        JPermolK,
        
        /// Energy rate in joules per second (J/s).
        JPers,
        
        /// Temperature in kelvins.
        K,
        
        /// Catalytic activity, katal = mol / s.
        kat,
        
        /// Catalytic activity concentration, katals per cubic metre.
        katPerm3,
        
        /// Mass in kilograms.  Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
        kg,
        
        /// Moment of mass in kilogram metres (kg·m) (first moment of mass). Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
        kgm,
        
        /// Moment of mass in kilogram square metres (kg·m˛) (Second moment of mass, commonly called the moment of inertia). Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
        kgm2,
        
        /// Weight per energy in kilograms per joule (kg/J). Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
        kgPerJ,
        
        /// Density in kilogram/cubic metres (kg/mł). Note: multiplier “k” is included in this unit symbol for compatibility with IEC 61850-7-3.
        kgPerm3,
        
        /// Speed, knots (1 kn = 1852/3600) m/s.
        kn,
        
        /// Temperature change rate in kelvins per second.
        KPers,
        
        /// Volume in litres, litre = dm3 = m3/1000.
        l,
        
        /// Luminous flux in lumens (cd·sr).
        lm,
        
        /// Volumetric flow rate, litres per hour.
        lPerh,
        
        /// Concentration, The ratio of the volume of a solute divided by the volume of  the solution. Note: Users may need use a prefix such a ‘µ’ to express a quantity such as ‘µL/L’.
        lPerl,
        
        /// Volumetric flow rate in litres per second.
        lPers,
        
        /// Illuminance in lux (lm/m˛).
        lx,
        
        /// Length in metres.
        m,
        
        /// Length, nautical miles (1 M = 1852 m).
        M,
        
        /// Area in square metres (m˛).
        m2,
        
        /// Viscosity in square metres / second (m˛/s).
        m2Pers,
        
        /// Volume in cubic metres (mł).
        m3,
        
        /// Volume, cubic metres, with the value compensated for weather effects.
        m3Compensated,
        
        /// Volumetric flow rate, cubic metres per hour.
        m3Perh,
        
        /// Specific volume, cubic metres per kilogram, v.
        m3Perkg,
        
        /// Volumetric flow rate in cubic metres per second (mł/s).
        m3Pers,
        
        /// Volume, cubic metres, with the value uncompensated for weather effects.
        m3Uncompensated,
        
        /// Time in minutes, minute  = 60 s.
        min,
        
        /// Pressure, millimetres of mercury (1 mmHg is approximately 133.3 Pa).
        mmHg,
        
        /// Amount of substance in moles.
        mol,
        
        /// Concentration, Molality, the amount of solute in moles and the amount of solvent in kilograms.
        molPerkg,
        
        /// Concentration, The amount of substance concentration, (c), the amount of solvent in moles divided by the volume of solution in mł.
        molPerm3,
        
        /// Concentration, Molar fraction, the ratio of the molar amount of a solute divided by the molar amount of the solution.
        molPermol,
        
        /// Fuel efficiency in metres per cubic metres (m/mł).
        mPerm3,
        
        /// Velocity in metres per second (m/s).
        mPers,
        
        /// Acceleration in metres per second squared (m/s˛).
        mPers2,
        
        /// Magnetic flux, maxwells (1 Mx = 10-8 Wb).
        Mx,
        
        /// Force in newtons (kg·m/s˛).
        N,
        
        /// Moment of force, newton metres.
        Nm,
        
        /// Dimension less quantity, e.g. count, per unit, etc.
        none,
        
        /// Surface tension, newton per metre.
        NPerm,
        
        /// Magnetic field in oersteds, (1 Oe = (103/4p) A/m).
        Oe,
        
        /// Electric resistance in ohms (V/A).
        ohm,
        
        /// Resistivity, ohm metres, (rho).
        ohmm,
        
        /// Electric resistance per length in ohms per metre ((V/A)/m).
        ohmPerm,
        
        /// Reciprocal of frequency (1/Hz).
        onePerHz,
        
        /// Wavenumber, reciprocal metres,  (1/m).
        onePerm,
        
        /// Pressure in pascals (N/m˛). Note: the absolute or relative measurement of pressure is implied with this entry. See below for more explicit forms.
        Pa,
        
        /// Pressure change rate in pascals per second.
        PaPers,
        
        /// Dynamic viscosity, pascal seconds.
        Pas,
        
        /// Concentration in parts per million.
        ppm,
        
        /// Quantity power, Q.
        Q,
        
        /// Quantity energy, Qh.
        Qh,
        
        /// Plane angle in radians (m/m).
        rad,
        
        /// Angular velocity in radians per second (rad/s).
        radPers,
        
        /// Angular acceleration, radians per second squared.
        radPers2,
        
        /// Amount of rotation, revolutions.
        rev,
        
        /// Rotations per second (1/s). See also Hz (1/s).
        rotPers,
        
        /// Time in seconds.
        s,
        
        /// Conductance in siemens.
        S,
        
        /// Conductance per length (F/m).
        SPerm,
        
        /// Time, Ratio of time.  Note: Users may need to supply a prefix such as ‘&#181;’ to show rates such as ‘&#181;s/s’.
        sPers,
        
        /// Solid angle in steradians (m2/m2).
        sr,
        
        /// Dose equivalent in sieverts (J/kg).
        Sv,
        
        /// Magnetic flux density in teslas (Wb/m2).
        T,
        
        /// Energy, therms.
        therm,
        
        /// Mass in tons, “tonne” or “metric  ton” (1000 kg = 1 Mg).
        tonne,
        
        /// Electric potential in volts (W/A).
        V,
        
        /// Volt squared (W˛/A˛).
        V2,
        
        /// Volt-squared hour, volt-squared-hours.
        V2h,
        
        /// Apparent power in volt amperes. See also real power and reactive power.
        VA,
        
        /// Apparent energy in volt ampere hours.
        VAh,
        
        /// Reactive power in volt amperes reactive. The “reactive” or “imaginary” component of electrical power (VIsin(phi)). (See also real power and apparent power).
        ///Note: Different meter designs use different methods to arrive at their results. Some meters may compute reactive power as an arithmetic value, while others compute the value vectorially. The data consumer should determine the method in use and the suitability of the measurement for the intended purpose.
        VAr,
        
        /// Reactive energy in volt ampere reactive hours.
        VArh,
        
        /// Volt-hour, Volt hours.
        Vh,
        
        /// Magnetic flux in volt per hertz.
        VPerHz,
        
        /// Electric field strength, volts per metre.
        VPerm,
        
        /// Voltage, ratio of voltages.  Note: Users may need to supply a prefix such as ‘m’ to show rates such as ‘mV/V’.
        VPerV,
        
        /// Power factor, PF, the ratio of the active power to the apparent power.  Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.
        VPerVA,
        
        /// Power factor, PF, the ratio of the active power to the apparent power. Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.
        VPerVAr,
        
        /// Volt seconds (Ws/A).
        Vs,
        
        /// Real power in watts (J/s). Electrical power may have real and reactive components. The real portion of electrical power (I&#178;R or VIcos(phi)), is expressed in Watts. See also apparent power and reactive power.
        W,
        
        /// Magnetic flux in webers (V·s).
        Wb,
        
        /// Real energy in watt hours.
        Wh,
        
        /// Active power per current flow, watts per Ampere.
        WPerA,
        
        /// Heat flux density, irradiance, watts per square metre.
        WPerm2,
        
        /// Radiance, watts per square metre steradian.
        WPerm2sr,
        
        /// Thermal conductivity in watt/metres kelvin.
        WPermK,
        
        /// Ramp rate in watts per second.
        WPers,
        
        /// Radiant intensity, watts per steradian.
        WPersr,
        
        /// Signal Strength, ratio of power.   Note: Users may need to supply a prefix such as ‘m’ to show rates such as ‘mW/W’.
        WPerW,
    }
}
