//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum WireMaterialKind {
        
        /// Aluminum-alloy conductor steel reinforced.
        aaac,
        
        /// Aluminum conductor steel reinforced.
        acsr,
        
        /// Aluminum wire.
        aluminum,
        
        /// Aluminum-alloy wire.
        aluminumAlloy,
        
        /// Aluminum-alloy-steel wire.
        aluminumAlloySteel,
        
        /// Aluminum-steel wire.
        aluminumSteel,
        
        /// Copper wire.
        copper,
        
        /// Other wire material.
        other,
        
        /// Steel wire.
        steel,
    }
}
