//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum WireInsulationKind {
        
        /// Asbestos and varnished cambric wire insulation.
        asbestosAndVarnishedCambric,
        
        /// Belted pilc wire insulation.
        beltedPilc,
        
        /// Butyl wire insulation.
        butyl,
        
        /// Crosslinked polyethylene wire insulation.
        crosslinkedPolyethylene,
        
        /// Ethylene propylene rubber wire insulation.
        ethylenePropyleneRubber,
        
        /// High nolecular weight polyethylene wire insulation.
        highMolecularWeightPolyethylene,
        
        /// High pressure fluid filled wire insulation.
        highPressureFluidFilled,
        
        /// Low capacitance rubber wire insulation.
        lowCapacitanceRubber,
        
        /// Oil paper wire insulation.
        oilPaper,
        
        /// Other kind of wire insulation.
        other,
        
        /// Ozone resistant rubber wire insulation.
        ozoneResistantRubber,
        
        /// Rubber wire insulation.
        rubber,
        
        /// Silicon rubber wire insulation.
        siliconRubber,
        
        /// Tree resistant high molecular weight polyethylene wire insulation.
        treeResistantHighMolecularWeightPolyethylene,
        
        /// Tree retardant crosslinked polyethylene wire insulation.
        treeRetardantCrosslinkedPolyethylene,
        
        /// Unbelted pilc wire insulation.
        unbeltedPilc,
        
        /// Varnished cambric cloth wire insulation.
        varnishedCambricCloth,
        
        /// Varnished dacron glass wire insulation.
        varnishedDacronGlass,
    }
}
