E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/FTN.legacy-rdfs -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/hazard_extension.xml -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/fire.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/storm.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/thunder.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/test0.ttl -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02.rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(1).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(2).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(3).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(4).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(5).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(6).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(7).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(8).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/10cimxml/Feeder_IEEE37v02_(9).rdf -input_file_type RDF -output_uri_prefix /triplestore/
