#title:drawHazard
#comment:

#tags:
#color:
#img:

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX custom: <http://www.custom.org/> 

SELECT DISTINCT ?g_wktHazardZone
WHERE {
	#hazard zones
	?hazardType rdfs:subClassOf+ custom:Hazard. 
	?hazardId a ?hazardType;
		custom:Hazard.DangerZone ?g_wktHazardZone.
}