#title:q-intersection
#comment:

#tags:geof:intersection
#color:ex-red
#img:400-data

select distinct ?intersect ?xGeom ?yGeom
where {
	?x geo:asWKT ?xGeom.
	?y geo:asWKT ?yGeom.
  
  BIND(geof:intersection(?xGeom, ?yGeom) as ?intersect)
  
  FILTER(str(?xGeom) < str(?yGeom))
}