#title:q-boundary
#comment:

#tags:geof:boundary,geof:convexHull
#color:ex-red
#img:400-data

select distinct ?boundary ?convexHull ?union
where {
	?x geo:asWKT ?xGeom.
	?y geo:asWKT ?yGeom.
  
  BIND(geof:union(?xGeom, ?yGeom) as ?union)
  BIND(geof:convexHull(?union) as ?convexHull)
  BIND(geof:boundary(?convexHull) as ?boundary)
  
  FILTER(str(?xGeom) < str(?yGeom))
}