#title:Get ACL segments
#comment:

#tags:aclSegment
#color:ex-green
#img:

SELECT DISTINCT ?name ?length ?mrid
WHERE {
  ?s cim:IdentifiedObject.name ?name.
  ?s rdf:type cim:ACLineSegment.
  ?s cim:Conductor.length ?length.
  ?s cim:IdentifiedObject.mRID ?mrid.
}
