#title:ask-optimized-draw-hazard
#comment:

#tags:ask,otimized,buffer,wkt,coordinates
#color:ex-blue
#img:

ASK {
	#hazard zones
	?hazardType rdfs:subClassOf+ custom:Hazard. 
	?hazardId a ?hazardType;
		custom:Hazard.DangerZone ?g_wktHazardZone.
}