E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/FTN.legacy-rdfs -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/hazard_extension.xml -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/fire.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/storm.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/thunder.ttl -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/ttl-data/test0.ttl -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02.rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(1).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(2).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(3).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(4).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(5).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(6).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(7).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(8).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(9).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(10).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(11).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(12).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(13).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(14).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(15).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(16).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(17).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(18).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(19).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(20).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(21).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(22).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(23).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(24).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(25).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(26).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(27).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(28).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(29).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(30).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(31).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(32).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(33).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(34).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(35).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(36).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(37).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(38).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(39).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(40).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(41).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(42).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(43).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(44).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(45).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(46).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(47).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(48).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(49).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(50).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(51).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(52).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(53).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(54).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(55).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(56).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(57).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(58).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(59).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(60).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(61).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(62).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(63).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(64).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(65).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(66).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(67).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(68).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(69).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(70).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(71).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(72).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(73).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(74).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(75).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(76).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(77).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(78).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(79).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(80).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(81).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(82).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(83).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(84).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(85).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(86).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(87).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(88).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(89).rdf -input_file_type RDF -output_uri_prefix /triplestore/

E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(90).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(91).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(92).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(93).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(94).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(95).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(96).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(97).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(98).rdf -input_file_type RDF -output_uri_prefix /triplestore/
E:/FAX/MasterTeza/MarkLogic/mlcp-10.0.6.1/bin/mlcp.bat import -mode local -host localhost -port 8111 -username admin -password admin -input_file_path C:/Users/DimitrijeMitic/Desktop/RedCrusaderJr-sparql-playground/test_folder/rdf-data/100cimxml/Feeder_IEEE37v02_(99).rdf -input_file_type RDF -output_uri_prefix /triplestore/

