#title: function-intersection
#comment: 

#tags:wkt,coordinates
#color:ex-blue
#img:


SELECT DISTINCT * WHERE
{ 
	BIND("POINT (0 0)" as ?point1Str).
	BIND(strdt(?point1Str, geo:wktLiteral) as ?wktPoint1).

	BIND("POLYGON ((0 0, 1 1, 0 1, 0 0))" as ?polygon2Str).
	BIND(strdt(?polygon2Str, geo:wktLiteral) as ?yellow_wktPolygon2).

	BIND("POLYGON ((0 0, 1 1, 1 0, 0 0))" as ?polygon3Str).
	BIND(strdt(?polygon3Str, geo:wktLiteral) as ?red_wktPolygon3).
  
  	BIND(geof:intersection(?yellow_wktPolygon2, ?red_wktPolygon3) as ?g_black_intersection_polygon23).
  	BIND(geof:intersection(?wktPoint1, ?yellow_wktPolygon2) as ?g_intersection_point1_polygon2).
}