#title: function-sym-difference
#comment: 

#tags:wkt,coordinates
#color:ex-red
#img:


SELECT DISTINCT * WHERE
{ 
    BIND("POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))" as ?polygon1Str).
	BIND(strdt(?polygon1Str, geo:wktLiteral) as ?black_wktPolygon1).

	BIND("POLYGON ((0 0, 1 1, 0 1, 0 0))" as ?polygon2Str).
	BIND(strdt(?polygon2Str, geo:wktLiteral) as ?yellow_wktPolygon2).
  
  	BIND(geof:symDifference(?black_wktPolygon1, ?yellow_wktPolygon2) as ?g_red_symDifference).
}