#title: function-buffer
#comment: 

#tags:wkt,coordinates
#color:ex-blue
#img:


SELECT DISTINCT * WHERE
{ 
    BIND("POINT (1 0)" as ?pointStr1).
	BIND(strdt(?pointStr1, geo:wktLiteral) as ?wktPoint1).
  
  	BIND("POLYGON ((0 0, 1 1, 0 1, 0 0))" as ?polygon2Str).
	BIND(strdt(?polygon2Str, geo:wktLiteral) as ?green_wktPolygon2).
  
  	BIND(geof:buffer(?wktPoint1, 10000, uom:metre) as ?g_red_pointBuffer).
  	BIND(geof:buffer(?green_wktPolygon2, 10000, uom:metre) as ?g_red_polygonBuffer).
}