#title: function-convex-hull
#comment: 

#tags:wkt,coordinates
#color:ex-blue
#img:


SELECT DISTINCT * WHERE
{ 
    BIND("POLYGON ((0 0, 0.5 0.5, 1 0, 1 1, 0 1, 0 0))" as ?polygon4Str).
	BIND(strdt(?polygon4Str, geo:wktLiteral) as ?green_wktPolygon4).
  
  	BIND(geof:convexHull(?green_wktPolygon4) as ?g_red_convexHull).
}