#title: function-distance
#comment: 

#tags:wkt,coordinates
#color:ex-blue
#img:


SELECT DISTINCT ?distance11 ?distance12 ?distance13 ?distance14 WHERE
{ 
    BIND("POINT (0 0)" as ?pointStr1).
	BIND(strdt(?pointStr1, geo:wktLiteral) as ?wktPoint1).
  
  	BIND("POINT (1 1)" as ?pointStr2).
	BIND(strdt(?pointStr2, geo:wktLiteral) as ?wktPoint2).
  
  	BIND("POINT (0 1)" as ?pointStr3).
	BIND(strdt(?pointStr3, geo:wktLiteral) as ?wktPoint3).
  
  	BIND("POINT (1 0)" as ?pointStr4).
	BIND(strdt(?pointStr4, geo:wktLiteral) as ?wktPoint4).
  
  	BIND(geof:distance(?wktPoint1, ?wktPoint1, uom:metre) as ?distance11).
  	BIND(geof:distance(?wktPoint1, ?wktPoint2, uom:metre) as ?distance12).
	BIND(geof:distance(?wktPoint1, ?wktPoint3, uom:metre) as ?distance13).
	BIND(geof:distance(?wktPoint1, ?wktPoint4, uom:metre) as ?distance14).
}
