#title: function-union
#comment: 

#tags:wkt,coordinates
#color:ex-blue
#img:


SELECT DISTINCT * WHERE
{ 
    BIND("POLYGON ((0 0, 1 1, 0 1, 0 0))" as ?polygon2Str).
	BIND(strdt(?polygon2Str, geo:wktLiteral) as ?green_wktPolygon2).

	BIND("POLYGON ((0 0, 1 1, 1 0, 0 0))" as ?polygon3Str).
	BIND(strdt(?polygon3Str, geo:wktLiteral) as ?green_wktPolygon3).
  
  	BIND(geof:union(?green_wktPolygon2, ?green_wktPolygon3) as ?g_yellow_union_polygon23).
}