#title:functions-boundary
#comment:

#tags:wkt,coordinates
#color:ex-red
#img:


SELECT DISTINCT * WHERE
{ 
    BIND("POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))" as ?polygon1Str).
	BIND(strdt(?polygon1Str, geo:wktLiteral) as ?black_wktPolygon1).
  
  	BIND(geof:boundary(?black_wktPolygon1) as ?g_red_boundary).
}